# Generated by Django 4.1.7 on 2023-11-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='City')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='Street')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Address')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='City')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='Street')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Address')),
            ],
        ),
    ]
